#---------------------------------------------------------------------------------------------------
# Twitch Controls Chaos (TCC) game configuration file
# Game: The Last of Us Part II (PS4)
#
# The settings defined here are those that are required to run a specific game through the Chaos
# engine. The basic settings for the engine itself are controlled in the chaosconfig.toml file.
# The syntax for this file is documented in chaosConfigFiles.md
#
# This file it the entry point for the PS4 version of TLOU2. It only defines the platform-specific
# configuraiton data for the game. Since the PS4 version is the reference version of the game
# against which TCC was developed, the only platform specific data here is a mod that is only
# uses a PS4-specific menu option.
#
# Note that if you edit this file while the chaos engine is running, you must reload the game
# so the chaos engine can re-read the updated file.
#---------------------------------------------------------------------------------------------------
# config_file_ver: Version string for the TCC game configuration format.
config_file_ver = "1.0"

chaos_toml = "main"

# game: User-friendly name of the game this configuration file defines.
game = "The Last of Us Part II (PS5)"

input_file = "tlou2-common.toml"

# This modifier only works if we're playing the OG game on a PS5.
[[modifier]]
name = "30 fps"
description = "Converting a PS5 to play like PS4"
type = "menu"
groups = [ "display" ]
menu_items = [{entry = "framerate", value = 0 }]
